// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using skterminal_fuel_skids_api.Configurations.Databases;

#nullable disable

namespace skterminal_fuel_skids_api.Migrations
{
    [DbContext(typeof(DataContextEntityFramework))]
    partial class DataContextEntityFrameworkModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<DateTimeOffset?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TagValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e1fce1f-f758-404c-9ab2-cda5f5115529"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 502, DateTimeKind.Unspecified).AddTicks(9705), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Asfalto",
                            Enabled = true,
                            Name = "Asfalto",
                            TagValue = 1
                        },
                        new
                        {
                            Id = new Guid("d078ae2f-73db-4ddc-b419-b2db4a900c73"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 502, DateTimeKind.Unspecified).AddTicks(9726), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gasolio",
                            Enabled = true,
                            Name = "Gasolio",
                            TagValue = 2
                        });
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Skid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<string>("Hub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Skids", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 21, 19, 45, 10, 924, DateTimeKind.Unspecified).AddTicks(4890), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Patín de Entrega",
                            Enabled = true,
                            Hub = "",
                            Order = 1,
                            ProductId = new Guid("7e1fce1f-f758-404c-9ab2-cda5f5115529"),
                            Tag = "PS"
                        },
                        new
                        {
                            Id = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 6, 30, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Patín de Recepción",
                            Enabled = true,
                            Hub = "",
                            Order = 2,
                            ProductId = new Guid("7e1fce1f-f758-404c-9ab2-cda5f5115529"),
                            Tag = "PE"
                        });
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidHourlyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("AcumMass")
                        .HasColumnType("double precision");

                    b.Property<double>("AcumVolCondBase")
                        .HasColumnType("double precision");

                    b.Property<double>("AcumVolNatural")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SkidId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SkidId");

                    b.ToTable("SkidHourlyReports", "public");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidHourlyReportByTrain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AverageCPL")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageCTL")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageCorrectedDensity")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageFactorK")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageFlow")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageMF")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageObservedDensity")
                        .HasColumnType("double precision");

                    b.Property<double?>("AveragePres")
                        .HasColumnType("double precision");

                    b.Property<double?>("AveragePresDens")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageTemp")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageTempDens")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<double?>("EndGrossTotalizer")
                        .HasColumnType("double precision");

                    b.Property<double?>("GrossVolume")
                        .HasColumnType("double precision");

                    b.Property<double?>("LineVolume")
                        .HasColumnType("double precision");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision");

                    b.Property<double?>("NetVolume")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SkidHourlyReportId")
                        .HasColumnType("uuid");

                    b.Property<double?>("StartGrossTotalizer")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("TrainId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkidHourlyReportId");

                    b.HasIndex("TrainId");

                    b.ToTable("SkidHourlyReportByTrains", "public");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<Guid>("SkidId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkidId");

                    b.HasIndex("TagId");

                    b.ToTable("SkidTags", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("021270b0-8375-4db3-8623-503a1ca4c7e3"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("a7e7b6a7-7b3b-4f2b-9d12-2b8abdb70d01")
                        },
                        new
                        {
                            Id = new Guid("049b4e83-251b-493e-bf51-6c48c344994b"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("a7e7b6a7-7b3b-4f2b-9d12-2b8abdb70d01")
                        },
                        new
                        {
                            Id = new Guid("085ac574-5e14-4348-99fa-ad1537b5b755"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("b8a6c5f2-3c44-4c7e-8a3a-5a1f6f0d2a02")
                        },
                        new
                        {
                            Id = new Guid("1b9b0f36-34a5-4fe9-9302-6349d4dcc62d"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("b8a6c5f2-3c44-4c7e-8a3a-5a1f6f0d2a02")
                        },
                        new
                        {
                            Id = new Guid("1feb427a-24f4-41f9-b8cf-49f5dcad5c81"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("c9b7d6e3-4d55-4d8f-9b4b-6b2f7f1e3b03")
                        },
                        new
                        {
                            Id = new Guid("235d1975-34ef-404e-95ec-b57ec91dd7b4"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("c9b7d6e3-4d55-4d8f-9b4b-6b2f7f1e3b03")
                        },
                        new
                        {
                            Id = new Guid("246adb38-98aa-4a9f-964c-2dbc7c9d1231"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("da08e7f4-5e66-4e90-ac5c-7c30802f4c04")
                        },
                        new
                        {
                            Id = new Guid("2c6a19cf-afb0-4bc8-89a4-5f0e73d6a527"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("da08e7f4-5e66-4e90-ac5c-7c30802f4c04")
                        },
                        new
                        {
                            Id = new Guid("333c900d-2263-438e-ac4d-0197d431148a"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("eb19f805-6f77-4191-bd6d-8d4191405d05")
                        },
                        new
                        {
                            Id = new Guid("436dfd11-1661-4e97-a16b-a9f66acd9bae"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("eb19f805-6f77-4191-bd6d-8d4191405d05")
                        },
                        new
                        {
                            Id = new Guid("6c3df0fc-be06-45c9-ac96-85821ebafedd"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("fc2a0916-7088-4292-ce7e-9e52a2516e06")
                        },
                        new
                        {
                            Id = new Guid("7a2cfae2-306f-4f9c-87e5-f14d8284a91e"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("fc2a0916-7088-4292-ce7e-9e52a2516e06")
                        },
                        new
                        {
                            Id = new Guid("7f280166-f777-4442-ac8c-0b6444d7e3d6"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("0d3b1a27-8199-4393-df8f-af63b3627f07")
                        },
                        new
                        {
                            Id = new Guid("a0d267f9-93be-4d93-9891-fd32668dbfc3"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("0d3b1a27-8199-4393-df8f-af63b3627f07")
                        },
                        new
                        {
                            Id = new Guid("b062fc2b-a512-464b-9d21-1867528dace4"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("1e4c2b38-92aa-44a4-e090-b074c4738008")
                        },
                        new
                        {
                            Id = new Guid("ca472a60-124e-4d93-9c7d-06514cd49d98"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("1e4c2b38-92aa-44a4-e090-b074c4738008")
                        },
                        new
                        {
                            Id = new Guid("e753f211-1188-4ab3-a03b-375945130185"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            TagId = new Guid("2f5d3c49-a3bb-45b5-f1a1-c185d5849109")
                        },
                        new
                        {
                            Id = new Guid("eeba331b-69ef-4188-b4f1-f9fc20509cd1"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 8, 5, 18, 0, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            TagId = new Guid("2f5d3c49-a3bb-45b5-f1a1-c185d5849109")
                        });
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("Display")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<double>("FloatingPrecision")
                        .HasColumnType("double precision");

                    b.Property<string>("MeasurementUnit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7e7b6a7-7b3b-4f2b-9d12-2b8abdb70d01"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(3), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Valores Generales",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "Kg/m³",
                            Order = 1,
                            TagName = "DENSIDAD"
                        },
                        new
                        {
                            Id = new Guid("b8a6c5f2-3c44-4c7e-8a3a-5a1f6f0d2a02"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(8), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Parámetro de operación",
                            Display = 1,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "L/m",
                            Order = 2,
                            TagName = "FLUJO_TREN1"
                        },
                        new
                        {
                            Id = new Guid("c9b7d6e3-4d55-4d8f-9b4b-6b2f7f1e3b03"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(11), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Parámetro de operación",
                            Display = 1,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "L/m",
                            Order = 3,
                            TagName = "FLUJO_TREN2"
                        },
                        new
                        {
                            Id = new Guid("da08e7f4-5e66-4e90-ac5c-7c30802f4c04"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(15), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Valores Generales",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "Kg/cm²",
                            Order = 4,
                            TagName = "PRESION_DENS"
                        },
                        new
                        {
                            Id = new Guid("eb19f805-6f77-4191-bd6d-8d4191405d05"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(19), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Parámetro de operación",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "Kg/cm²",
                            Order = 5,
                            TagName = "PRESION_TREN1"
                        },
                        new
                        {
                            Id = new Guid("fc2a0916-7088-4292-ce7e-9e52a2516e06"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(22), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Parámetro de operación",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "Kg/cm²",
                            Order = 6,
                            TagName = "PRESION_TREN2"
                        },
                        new
                        {
                            Id = new Guid("0d3b1a27-8199-4393-df8f-af63b3627f07"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(26), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Valores Generales",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "°C",
                            Order = 7,
                            TagName = "TEMP_DENS"
                        },
                        new
                        {
                            Id = new Guid("1e4c2b38-92aa-44a4-e090-b074c4738008"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(34), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Parámetro de operación",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "°C",
                            Order = 8,
                            TagName = "TEMP_TREN1"
                        },
                        new
                        {
                            Id = new Guid("2f5d3c49-a3bb-45b5-f1a1-c185d5849109"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 9, 30, 21, 24, 35, 504, DateTimeKind.Unspecified).AddTicks(37), new TimeSpan(0, 0, 0, 0, 0)),
                            DataType = "Parámetro de operación",
                            Display = 0,
                            Enabled = true,
                            FloatingPrecision = 2.0,
                            MeasurementUnit = "°C",
                            Order = 9,
                            TagName = "TEMP_TREN2"
                        });
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<string>("Hub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SkidId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SkidId");

                    b.ToTable("Trains", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04ab1c49-499f-42f1-87f3-27fec25b7448"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 21, 19, 46, 54, 59, DateTimeKind.Unspecified).AddTicks(2330), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tren 110",
                            Enabled = true,
                            Hub = "",
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            Tag = "T-110"
                        },
                        new
                        {
                            Id = new Guid("4dc56c37-49c7-4e41-b1bd-103cdf9f464e"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 21, 19, 50, 13, 496, DateTimeKind.Unspecified).AddTicks(8460), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tren 113",
                            Enabled = true,
                            Hub = "",
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            Tag = "T-113"
                        },
                        new
                        {
                            Id = new Guid("5412d106-bd15-44f2-abb5-6a1535731a59"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 21, 19, 49, 38, 521, DateTimeKind.Unspecified).AddTicks(6720), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tren 112",
                            Enabled = true,
                            Hub = "",
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            Tag = "T-112"
                        },
                        new
                        {
                            Id = new Guid("5471e05c-186e-438b-96e7-295f4020301f"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 16, 23, 0, 9, 18, DateTimeKind.Unspecified).AddTicks(2810), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tren 101",
                            Enabled = true,
                            Hub = "",
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            Tag = "T-101"
                        },
                        new
                        {
                            Id = new Guid("55c52bc6-84eb-4f8b-9566-68576fa4f8a5"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 16, 22, 59, 29, 60, DateTimeKind.Unspecified).AddTicks(9440), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tren 100",
                            Enabled = true,
                            Hub = "",
                            SkidId = new Guid("3e18ebd2-b998-4e52-96ff-e2d7975ead73"),
                            Tag = "T-100"
                        },
                        new
                        {
                            Id = new Guid("eb3575e1-96d5-42f8-a0f3-feae76d005e7"),
                            CreationDate = new DateTimeOffset(new DateTime(2025, 7, 21, 19, 48, 58, 504, DateTimeKind.Unspecified).AddTicks(1050), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tren 111",
                            Enabled = true,
                            Hub = "",
                            SkidId = new Guid("32368847-78ab-4bf7-ab01-5ae54f957340"),
                            Tag = "T-111"
                        });
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.TrainTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("TRUE");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TrainId");

                    b.ToTable("TRainTags", "public");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Skid", b =>
                {
                    b.HasOne("skterminal_fuel_skids_api.Models.Product", "Product")
                        .WithMany("SkidsList")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidHourlyReport", b =>
                {
                    b.HasOne("skterminal_fuel_skids_api.Models.Product", "Product")
                        .WithMany("SkidHourlyReportList")
                        .HasForeignKey("ProductId");

                    b.HasOne("skterminal_fuel_skids_api.Models.Skid", "Skid")
                        .WithMany("SkidHourlyReportList")
                        .HasForeignKey("SkidId");

                    b.Navigation("Product");

                    b.Navigation("Skid");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidHourlyReportByTrain", b =>
                {
                    b.HasOne("skterminal_fuel_skids_api.Models.SkidHourlyReport", "SkidHourlyReport")
                        .WithMany("SkidHourlyReportByTrainList")
                        .HasForeignKey("SkidHourlyReportId");

                    b.HasOne("skterminal_fuel_skids_api.Models.Train", "Train")
                        .WithMany("SkidHourlyReportByTrainList")
                        .HasForeignKey("TrainId");

                    b.Navigation("SkidHourlyReport");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidTag", b =>
                {
                    b.HasOne("skterminal_fuel_skids_api.Models.Skid", "Skids")
                        .WithMany("SkidTagsList")
                        .HasForeignKey("SkidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skterminal_fuel_skids_api.Models.Tag", "Tags")
                        .WithMany("SkidTagsList")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skids");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Train", b =>
                {
                    b.HasOne("skterminal_fuel_skids_api.Models.Skid", "Skid")
                        .WithMany("TrainList")
                        .HasForeignKey("SkidId");

                    b.Navigation("Skid");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.TrainTag", b =>
                {
                    b.HasOne("skterminal_fuel_skids_api.Models.Tag", "Tags")
                        .WithMany("TrainTagsList")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skterminal_fuel_skids_api.Models.Train", "Trains")
                        .WithMany("TrainTagsList")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tags");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Product", b =>
                {
                    b.Navigation("SkidHourlyReportList");

                    b.Navigation("SkidsList");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Skid", b =>
                {
                    b.Navigation("SkidHourlyReportList");

                    b.Navigation("SkidTagsList");

                    b.Navigation("TrainList");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.SkidHourlyReport", b =>
                {
                    b.Navigation("SkidHourlyReportByTrainList");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Tag", b =>
                {
                    b.Navigation("SkidTagsList");

                    b.Navigation("TrainTagsList");
                });

            modelBuilder.Entity("skterminal_fuel_skids_api.Models.Train", b =>
                {
                    b.Navigation("SkidHourlyReportByTrainList");

                    b.Navigation("TrainTagsList");
                });
#pragma warning restore 612, 618
        }
    }
}
